version: 2.1

environment:
  DOCKERHUB_USER: "barongal"
  DOCKERHUB_PASSWD: "temporaryp4ssw0rd"

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      # Check out the code
      - checkout

      # Build the app and database images
      - run:
          name: Build Docker image
          command: docker build -t go-todo-app .

      # Push the images to Docker Hub
      - run:
          name: Push image to Docker Hub
          command: bash push-images-to-docker-hub.sh $DOCKERHUB_USER $DOCKERHUB_PASSWD

  deploy:
    docker:
      - image: docker:latest

    steps:
      # Check out the code
      - checkout

      # Install Helm
      - run:
          name: Install Helm
          command: |
            apk add --update bash curl ca-certificates git
            curl -LO https://git.io/get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh

      # Deploy the app and database charts to Kubernetes
      - run:
          name: Deploy charts to Kubernetes
          command: |
            helm init --wait
            helm upgrade -i go-todo-app ./helm/go-todo-app
            helm upgrade -i go-todo-db ./helm/go-todo-db

      # Add the hosts entry
      - run:
          name: Add hosts entry
          command: bash add-hosts-entry.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build